### ISSUE TITLE
[BUG] Referenced properties are not rendered after switching between Aspects

### ISSUE THREAD

**Issue by Kostadin-Ivanov** [eclipse-esmf/esmf-aspect-model-editor#71] opened 2023-07-21 10:07 UTC
**Describe the bug**
I have two aspect models in my workspace. One - Vehicle.ttl is the main one, and the second - CurrentLocation.ttl is kind of a secondary model, which is referenced as property within the Vehicle.ttl.
The problem is that, after I saved my Vechicle.ttl model and loaded the CurrentLocation.ttl one in my editor, then when I load back the Vehicle.ttl one, the referenced property for currentLocation is not displayed in the editor. Even that it is visible within the ttl file. 

**Where**
In the Aspect Model Editor - v4.5.0.

**Screenshots**
I tried to add some screenshots but for some reason I keep getting the: "something went really wrong, and we can't process that file. Try again" message.
I tried to upload PNG and JPEG, same result as above.

**Additional context**
Steps to reproduce:

1. Load AME with 2 TTL models in its workspace - 1st main - ModelA and and 2nd ModelB.
2. Load ModelA
3. then add ModelB - either a property from it, or the whole graph as property to ModelA
4. Save ModelA in workspace and load ModelB
5. Load again ModelA

**EXPECTED** ModelA graph is loaded and the references property for modelB is also displayed

**ACTUAL** The property - :modelB is not displayed, although when I check the contents of the ModelA .ttl file, it was rendered there as:
`:ModelAEntity a samm:Entity;
    samm:properties (:modelB).`

**Observed in:**
AME version 4.5.0 - Windows OS

**Comment by georgemoscu** [comment] 2023-07-24 12:28
Hey @Kostadin-Ivanov 
This behavior is expected. The elements from other files can be imported into the Aspect Model Editor view but they are not referenced into the actual model until they are connected to an element from the current loaded model

**Comment by Kostadin-Ivanov** [comment] 2023-07-24 12:46
Hello @georgemoscu , 
I am not sure if I follow you.

The described problem is that, I imported a property from the secondary model to my main one - ModelA, and **indeed** I did link it to my model entity as a property. I saved + overwrite as normal, but then when I switched between models, the new - imported property was not rendered.
The property is correctly set up in the ModelA.ttl, because when I open it in editor, I can see the property declaration, as described in the **ACTUAL** part of this ticket description.

Unfortunately, for some reason I cannot add screenshots for better illustration of the issue.

**Comment by Kostadin-Ivanov** [comment] 2023-07-24 14:55
Hello @georgemoscu ,
I wanted to let you know that I just tested this bug on AME 4.4.1 for windows and it was working fine, i.e. the referenced properties were rendered and visible in my editor.

**Comment by chris-volk** [comment] 2023-07-25 12:54
Thanks @Kostadin-Ivanov .
Closing as "cannot reproduce in new version"

**Comment by michelu89** [comment] 2023-08-18 13:43
Will be ready on version 4.5.1

**Closed by michelu89** 2023-08-18 13:43 UTC
Labels: bug, acknowledged
